<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Medistock.Domain\Medistock.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Medistock.Application\Medistock.Application.csproj" />
    <ProjectReference Include="..\Medistock.Infrastructure.Data\Medistock.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\..\Shared\Medistock.Contracts\Medistock.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
